# Generated by Django 4.2.4 on 2023-08-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
